Repository rpj09/FRIDAY-virtual-assistant, pull requests merged in 2022-10, with the labels that each got.

#5 modified: F.R.I.D.A.Y-windows/FRIDAY.py
  F.R.I.D.A.Y-windows/FRIDAY.py
Labels: hacktoberfest, hacktoberfest-accepted

#6 Improved the readme file and added some documentation
  F.R.I.D.A.Y-windows/requirements.txt
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#7 Added some features
  F.R.I.D.A.Y-linux/FRIDAY.py
  F.R.I.D.A.Y-linux/requirements.txt
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#8 updated both version fixed some bugs
  F.R.I.D.A.Y-linux/FRIDAY.py
  F.R.I.D.A.Y-windows/FRIDAY.py
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#9 Enhancements
  F.R.I.D.A.Y-linux/FRIDAY.py
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#10 Update the vesions for linux and windows
  F.R.I.D.A.Y-linux/requirements.txt
  F.R.I.D.A.Y-windows/FRIDAY.py
  F.R.I.D.A.Y-windows/requirements.txt
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted
